import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/components/Header/Header";
import "../styles/normalize.css";
import "../styles/globals.scss";

const robotoBold = localFont({
  src: "./fonts/Roboto-Bold.ttf",
  variable: "--font-roboto-bold",
  weight: "700",
});
const robotoLight = localFont({
  src: "./fonts/Roboto-Light.ttf",
  variable: "--font-roboto-light",
  weight: "700",
});
const robotoMedium = localFont({
  src: "./fonts/Roboto-Medium.ttf",
  variable: "--font-roboto-medium",
  weight: "700",
});
const robotoRegular = localFont({
  src: "./fonts/Roboto-Regular.ttf",
  variable: "--font-roboto-regular",
  weight: "700",
});

export const metadata: Metadata = {
  title: "CSoft Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${robotoRegular.variable} ${robotoRegular.variable}`}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
